const articles = [ {
    name: 'learn-react',
    title: 'The Fastest Way to Learn React',
    content: [ "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed convallis ligula eget turpis pretium mollis. Aenean ac turpis ipsum. Morbi augue metus, posuere non mi in, facilisis feugiat tellus. Morbi rutrum ex sit amet turpis mattis fringilla. Maecenas mauris arcu, viverra a nisl ac, tincidunt gravida quam. Praesent tellus ipsum, bibendum a maximus sed, porttitor id velit. Nunc non arcu sit amet arcu ornare bibendum.Nam sollicitudin venenatis enim. Phasellus rutrum erat ut metus vestibulum consectetur. Ut accumsan nunc ac rutrum porttitor. Etiam sagittis pulvinar vehicula. Etiam tempus nisl vel nunc tincidunt laoreet. Nunc ut ultricies odio, eget lobortis quam. Cras feugiat, magna iaculis pharetra eleifend, sem eros tristique dui, a ultricies erat tortor vel enim.Aliquam dignissim turpis eget congue sodales. Donec rhoncus interdum dignissim. Curabitur eu massa erat. Maecenas congue, orci nec ultrices laoreet, ipsum tellus placerat arcu, in mattis odio metus eget diam. Maecenas est quam, porta quis iaculis eget, dapibus quis enim. Sed eu pharetra mauris, et tristique risus. Aenean non condimentum elit. Praesent sit amet tortor consectetur ipsum tempus fringilla sed varius ex. Sed in libero vel est venenatis commodo. Fusce porttitor mauris ut est scelerisque, ac consequat diam rutrum. Aliquam in magna euismod, faucibus ex et, tempor nibh.Proin dapibus mattis posuere. Proin volutpat metus magna, in suscipit diam dictum vel. Proin cursus laoreet quam. Sed lobortis ipsum eget elit varius, et eleifend turpis posuere." ]
}, {
    name: 'mongodb',
    title: 'Learn MongoDB',
    content: [ 'Proin dapibus mattis posuere. Proin volutpat metus magna, in suscipit diam dictum vel. Proin cursus laoreet quam. Sed lobortis ipsum eget elit varius, et eleifend turpis posuere. Nullam vitae accumsan enim, vel lacinia diam. Morbi purus tortor, tincidunt in consequat a, dapibus vel arcu. Praesent cursus elit massa, blandit rhoncus sem suscipit vitae. Donec commodo, lectus sit amet consectetur ultricies, lacus ex sollicitudin dolor, sed euismod erat lectus in massa. Sed lacinia neque id odio lobortis, et lobortis dui tristique. Aliquam in porttitor ante. Curabitur volutpat facilisis leo, in feugiat ipsum tempus sit amet. Mauris maximus ligula accumsan orci semper, vitae sodales odio aliquet. Integer efficitur orci id leo facilisis pulvinar. Maecenas condimentum maximus ipsum quis ultrices. Nulla pellentesque mauris eu enim euismod, sed condimentum neque scelerisque.Vestibulum dignissim risus non mi facilisis, vitae facilisis augue gravida. Vestibulum consectetur, tortor non malesuada eleifend, turpis lacus molestie massa, quis congue tortor est non mauris. Sed accumsan lorem justo, at pretium mi elementum id. In in tempor sapien. Ut feugiat eros sollicitudin commodo convallis. Donec sem sem, laoreet non eros in, dictum eleifend metus. Praesent sed iaculis nulla. Praesent dignissim quam nec consectetur porta. Aenean id lectus dapibus, ultricies sem vitae, fermentum enim. Donec gravida, sapien nec finibus suscipit, eros dui lobortis velit, eu aliquam nunc massa id urna. Praesent nec lacus eget dui suscipit aliquam mattis at dolor. Aenean erat erat, maximus non nunc quis, mattis ornare lectus. Vivamus luctus risus malesuada commodo bibendum.' ]
},
{
    name: 'full-stack development',
    title: 'Be a Full-stack Developer',
    content: [ 'Sed blandit eu justo quis congue. Cras eleifend tempus est non ornare. Suspendisse quis est lacinia, ultrices mauris vitae, placerat tortor. Curabitur eleifend consectetur est, in pellentesque risus tempor vitae. Etiam interdum ornare turpis sed tempus. Suspendisse vestibulum tincidunt sapien id volutpat. Sed elementum lacus nec est congue, vel sagittis tortor eleifend. Vivamus id sollicitudin massa, iaculis pharetra turpis. Proin viverra ac nisl quis vulputate. Vestibulum ut elementum eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut dapibus libero quis pellentesque dapibus. Mauris condimentum in dolor sit amet iaculis.Maecenas eget neque erat. Nulla odio urna, vestibulum ut egestas id, hendrerit vel erat. Curabitur maximus quam ut erat sollicitudin feugiat. Praesent sit amet erat vehicula, varius lacus nec, molestie odio. Vestibulum ultricies congue condimentum. Pellentesque eu ipsum non nibh ullamcorper pellentesque sed eu nulla. Sed convallis fringilla arcu. Ut ac lacus turpis. Donec posuere, augue et elementum venenatis, mauris libero sagittis nisl, in pellentesque ex erat quis odio. Suspendisse potenti.' ]
} ];

export default articles;